CREATE TABLE IF NOT EXISTS projects(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <> ''),
  priority INTEGER NOT NULL,
  description text,
  deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL CHECK (name <> ''),
  done BOOLEAN,
  projectid INTEGER REFERENCES projects(id)
);

INSERT INTO projects(name, priority, description, deliverydate)
  VALUES('Maker a web App', 1, 'Using Javascript', '2019-05-12');

INSERT INTO projects(name, priority, description, deliverydate)
  VALUES('Maker App', 1, 'Using Dart', '2019-05-13');

INSERT INTO projects(name, priority, description, deliverydate)
  VALUES('Maker Test', 1, 'Using Clipper', '2019-05-17');

INSERT INTO tasks(name, done, projectid)
  VALUES('donwload Vuejs', false, 1);

INSERT INTO tasks(name, done, projectid)
  VALUES('Create UI WEB', false, 1);

INSERT INTO tasks(name, done, projectid)
  VALUES('Download Flutter', false, 2);  

INSERT INTO tasks(name, done, projectid)
  VALUES('Desing Device Flutter', false, 2);  

